name: Run Python Scripts Daily and Manually

on:
  schedule:
    - cron: '59 23 * * *'  
  workflow_dispatch: 

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Instala as dependências a partir do requirements.txt

    - name: Run KOMMO.py
      run: python KOMMO.py  # Executa o script KOMMO.py

    - name: Run PIPE.py
      run: python PIPE.py  # Executa o script PIPE.py
